services:
  postgres:
    image: postgres:16.4
    container_name: TestTaskDB
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app-network

  elasticsearch:
    image: elasticsearch:8.15.0
    container_name: TestTaskES
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    env_file:
      - .env
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  web:
    image: apsolutions_task
    container_name: TestTaskFA
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PWD: ${DB_PWD}
      DB_NAME: ${DB_NAME}
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
